module.exports = {
  data: [
    {
      question: "Who was King Ahab's wife?",
      option1: "Ruth",
      option2: "Mary",
      option3: "Jezebel",
      option4: "Rebecca",
      ans: 3,
    },
    {
      question: "Who led the Israelites into the Promised Land?",
      option1: "Moses",
      option2: "Joshua",
      option3: "Abraham",
      option4: "Isaac",
      ans: 2,
    },
    {
      question: "Who was thrown into a lion's den?",
      option1: "David",
      option2: "Solomon",
      option3: "Daniel",
      option4: "Joseph",
      ans: 3,
    },
    {
      question: "Who killed Goliath?",
      option1: "Saul",
      option2: "David",
      option3: "Samson",
      option4: "Jonathan",
      ans: 2,
    },
    {
      question: "Who was sold into slavery by his brothers?",
      option1: "Moses",
      option2: "Aaron",
      option3: "Joseph",
      option4: "Simon",
      ans: 3,
    },
    {
      question: "Who was the first king of Israel?",
      option1: "Saul",
      option2: "David",
      option3: "Solomon",
      option4: "Samuel",
      ans: 1,
    },
    {
      question: "Who interpreted dreams in Egypt?",
      option1: "Joseph",
      option2: "Daniel",
      option3: "Moses",
      option4: "Pharaoh",
      ans: 1,
    },
    {
      question: "Who built the ark?",
      option1: "Noah",
      option2: "Moses",
      option3: "Abraham",
      option4: "Jacob",
      ans: 1,
    },
    {
      question: "Who was swallowed by a great fish?",
      option1: "Jonah",
      option2: "Peter",
      option3: "James",
      option4: "John",
      ans: 1,
    },
    {
      question: "Who was the strongest man in the Bible?",
      option1: "Goliath",
      option2: "Samson",
      option3: "David",
      option4: "Saul",
      ans: 2,
    },
    {
      question: "Who baptized Jesus?",
      option1: "Peter",
      option2: "Paul",
      option3: "John the Baptist",
      option4: "James",
      ans: 3,
    },
    {
      question: "Who was the first disciple to be martyred?",
      option1: "Stephen",
      option2: "James",
      option3: "Peter",
      option4: "John",
      ans: 2,
    },
    {
      question: "Who wrote the book of Revelation?",
      option1: "Paul",
      option2: "Peter",
      option3: "John",
      option4: "James",
      ans: 3,
    },
    {
      question: "Who was the first man created?",
      option1: "Adam",
      option2: "Eve",
      option3: "Cain",
      option4: "Abel",
      ans: 1,
    }
  ],
};
